spring.application.name=foodapi
server.port=2026

#mongodb configuration
spring.mongodb.uri=${MONGODB_URL}

#aws config
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.bucketname=${AWS_BUCKET_NAME}